import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "antd/dist/reset.css";

const appSans = localFont({
  src: [
    { path: "../public/fonts/Inter-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/Inter-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-app-sans",
  display: "swap",
});

const appMono = localFont({
  src: [
    { path: "../public/fonts/LXGWWenKaiMono-Medium.ttf", weight: "500", style: "normal" },
  ],
  variable: "--font-app-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={
        `${appSans.className} 
        ${appMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
