import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import "@/app/globals.css";
import "antd/dist/reset.css";

import LayoutClientBridge from "@/app/components/LayoutClientBridge";


const appSans = localFont({
  src: [
    { path: "../public/fonts/Inter-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/Inter-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-app-sans",
  display: "swap",
});

const appMono = localFont({
  src: [
    { path: "../public/fonts/LXGWWenKaiMono-Medium.ttf", weight: "500", style: "normal" },
  ],
  variable: "--font-app-mono",
  display: "swap",
});

export const metadata: Metadata = {
  icons: {
    icon: "/public/cxkd.png",
    // shortcut: "/favicon.ico",
    // apple: "/apple-icon.png",
  },
  title: {
    default: "箱根駅伝予測",
    template: "%s | 箱根駅伝予測",
  },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="zh-CN">
      <body className={
        `
        ${appSans.variable} ${appMono.variable}  antialiased`
      }>
        
        <LayoutClientBridge fontSansClass={appSans.className} fontMonoClass={appMono.className} />

          <main className="mainContent">
            {children}
          </main>
  
      </body>
    </html>
  );
}
